name: ExilePearl
version: 1.6.0-SNAPSHOT
main: net.civmc.ExilePearl.ExilePearlPlugin
depend: [CivModCore]
softdepend: [NameLayer, Citadel, Bastion, CivChat2, JukeAlert, CombatTagPlus, RandomSpawn, WorldBorder, MythicMobs, Brewery, BanStick]
commands:
  ep:
  suicide:
  pp:
    description: Legacy prison pearl commands
    aliases: [pplocate, ppl, ppfree, ppf, ppbroadcast, ppb, ppconfirm, ppsilence]
api-version: 1.14
