name: ${pluginName}
version: ${version}
authors: [ProgrammerDan, Gordon]
main: com.devotedmc.ExilePearl.ExilePearlPlugin
description: ${description}
api-version: ${api_version}
depend: [CivModCore]
softdepend: [NameLayer, Citadel, Bastion, CivChat2, JukeAlert, CombatTagPlus, RandomSpawn, WorldBorder, MythicMobs, Brewery, BanStick]
commands:
  ep:
  suicide:
  pp:
    description: Legacy prison pearl commands
    aliases: [pplocate, ppl, ppfree, ppf, ppbroadcast, ppb, ppconfirm, ppsilence]
